# Generated by Django 5.0.6 on 2024-05-24 10:12

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('ACT', 'Action'), ('ADV', 'Adventure'), ('ANI', 'Animation'), ('COM', 'Comedy'), ('CRI', 'Crime'), ('DOC', 'Documentary'), ('DRA', 'Drama'), ('FAM', 'Family'), ('FAN', 'Fantasy'), ('HIS', 'History'), ('HOR', 'Horror'), ('MUS', 'Music'), ('MYS', 'Mystery'), ('ROM', 'Romance'), ('SF', 'Science Fiction'), ('TVM', 'TV Movie'), ('THR', 'Thriller'), ('WAR', 'War'), ('WES', 'Western')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.UUID('f92dbcef-9b1a-4380-a612-e3ed7fbd6efd'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.UUIDField(default=uuid.UUID('c7505c0e-0256-436c-a057-fe0a62d99bf6'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField()),
                ('customer', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite_list',
            fields=[
                ('favorite_list_id', models.UUIDField(default=uuid.UUID('371bf98b-dbba-4039-b207-8393947a685e'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.UUID('b44a612f-7772-464f-a3d4-cad30a3d7a8b'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.UUIDField(default=uuid.UUID('a247537c-1357-41ce-81d5-aba3be82d4de'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trailer_url', models.CharField(verbose_name=100)),
                ('vote_average', models.DecimalField(decimal_places=3, max_digits=4)),
                ('poster_path', models.URLField(blank=True)),
                ('backdrop_path', models.URLField(blank=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cart')),
                ('favorite_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.favorite_list')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.UUID('5945a326-2e93-4c92-8cca-1b2f04b4253a'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('payment_method', models.CharField(choices=[('PP', 'PayPal'), ('ST', 'STRIPE')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.payment'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('avatar', models.ImageField(default='default.jpg', upload_to='media/uploads')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.movie')),
            ],
            options={
                'unique_together': {('movie', 'category')},
            },
        ),
    ]
