# Generated by Django 5.0.6 on 2024-05-21 14:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_movie_category_alter_cart_cart_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.UUIDField(default=uuid.UUID('471f0676-68a8-4211-a110-1f88edcec5f8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.UUIDField(default=uuid.UUID('0566c93c-eca7-4d79-a446-c447922065a2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.UUIDField(default=uuid.UUID('a181c1b9-48a9-4472-a28a-0be6964aa922'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='favorite_list',
            name='favorite_list_id',
            field=models.UUIDField(default=uuid.UUID('38195bb7-a43d-4fbc-b91b-460691b3415e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.UUIDField(default=uuid.UUID('a0dde497-eed7-49c3-8d74-e35fa95985a4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('a2ba458a-ec19-433a-afdc-e9710c9123d1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('a93ace40-fb83-4992-95bb-25bf8680d0b5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
