# Generated by Django 5.0.6 on 2024-05-21 15:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cart_cart_id_alter_category_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.UUIDField(default=uuid.UUID('6218b1d9-d081-4ae5-af3f-f90363a73a86'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.UUIDField(default=uuid.UUID('a2a52d87-aa58-4701-a9e4-9d70b8504f08'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.UUIDField(default=uuid.UUID('6a691123-103c-4445-9d69-589ef64931b9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='favorite_list',
            name='favorite_list_id',
            field=models.UUIDField(default=uuid.UUID('33c16da7-8bd7-4a2d-bedf-5575ae12f8d1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cart'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='favorite_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.favorite_list'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.UUIDField(default=uuid.UUID('a3304eaa-3280-43e7-b756-94c4a39cb8bd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('73556d69-c9a1-4406-80ef-8ba185673c29'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('1bd4bdd3-1e2c-4851-8f08-c5e68bdeaefe'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
