# Generated by Django 5.0.6 on 2024-05-22 09:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cart_cart_id_alter_category_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.UUIDField(default=uuid.UUID('898fa6f0-b26b-4b67-a14e-b34f52ed7296'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('ACT', 'Action'), ('ADV', 'Adventure'), ('ANI', 'Animation'), ('COM', 'Comedy'), ('CRI', 'Crime'), ('DOC', 'Documentary'), ('DRA', 'Drama'), ('FAM', 'Family'), ('FAN', 'Fantasy'), ('HIS', 'History'), ('HOR', 'Horror'), ('MUS', 'Music'), ('MYS', 'Mystery'), ('ROM', 'Romance'), ('SF', 'Science Fiction'), ('TVM', 'TV Movie'), ('THR', 'Thriller'), ('WAR', 'War'), ('WES', 'Western')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.UUIDField(default=uuid.UUID('f305d99c-fc51-437d-bbf3-43437ea60a2b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='favorite_list',
            name='favorite_list_id',
            field=models.UUIDField(default=uuid.UUID('c52f8f69-cd61-404a-b819-5d881ed3a505'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.UUIDField(default=uuid.UUID('248b8395-7064-49da-9c36-6efee4cbb319'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('947876ed-0a80-4975-b287-7b27c02f29c7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('4058081e-25d6-4fd1-b2aa-bb187f8a778c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
